### ISSUE TITLE
Expand Documentation around CQL Configuration in application.yaml

### ISSUE THREAD

**Issue by AndyStevens98** [DBCG/cqf-ruler#565]
The application.yaml contains the following properties:
```
cql:
         enabled: true
         engine:
            debug_logging_enabled: false
            options: "EnableExpressionCaching"
         use_embedded_libraries: true
         translator:
            analyzeDataRequirements: false
            collapseDataRequirements: true
         options: "EnableAnnotations,EnableLocators,DisableListDemotion,DisableListPromotion"
```
It would be great if documentation could be written around what each of these mean in the context of CQF Ruler
